[package]
name = "actix-jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
serde_json = "1.0.120"
# JWT
chrono = "0.4.38"
jsonwebtoken = "9.3.0"
serde = { version = "1.0.204", features = ["derive"] }